web:
    image: tutum/apache-php
    ports:
        - "80:80"
    volumes:
        - /web:/app
        - /conf/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
 ###       - /conf/site:/etc/apache2/sites-enabled
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - db:db
        - maildev:maildev

maildev:
    image: djfarrelly/maildev
    ports:
       - "1080:80"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
       - "1081:8080"
    links:
       - db:db
    environment:
        - mysql_db_server:db
db:
    image: mysql
    volumes:
        - /var/lib/boot2docker/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root